apiVersion: v1
kind: Service
metadata:
  name: reelcruit-candidate-svc
  namespace: production
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: reelcruit-candidate
