version: '3.8'

services:
  admin-frontend:
    container_name: reelcruitapp/reelcruit-candidate-frontend
    image: reelcruitapp/reelcruit-candidate-frontend
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      network: host
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: http://a5681aa47982f4f468de8bf939d68d1f-2012857988.ca-central-1.elb.amazonaws.com/api
      NODE_ENV: Production
